olade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers


from users.views import UserLoginView
from courses.api_views import CourseApiViewSet, NewEnrolleeApiViewSet
from discounts.api_views import DiscountApiViewSet


# set up rest framework router
router = routers.DefaultRouter()
router.register(r'courses', CourseApiViewSet)
router.register(r'new-enrollee', base_name='new-enrollee', viewset=NewEnrolleeApiViewSet)
router.register(r'discount', DiscountApiViewSet)

# overwrite admin template variables
admin.site.site_header = 'Olade Administration'                    # default: "Django Administration"
admin.site.index_title = 'Administration'                 # default: "Site administration"
admin.site.site_title = 'Olade site admin'      # default: "Django site admin"

urlpatterns = [
    path('', UserLoginView.as_view()),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

payments/urls.py
from django.urls import path
from .views import PaymentHistoryView

app_name = 'payments'

urlpatterns = [
    path('payment-history', PaymentHistoryView.as_view(), name='payment-history'),
]

payments/models.py
from django.db import models
from django.conf import settings
from courses.models import Enrolled
from discounts.models import Discount


PAYMENT_TYPE_CHOICES = (
    ('stripe', 'Online Payment (Stripe)'),
    ('cash', 'Cash'),
    ('money-transfer', 'Money Transfer'),
    ('cheque', 'Cheque'),
    ('other', 'Other'),
)


def increment_reference_number():
    last_payment = PaymentLog.objects.all().order_by('id').last()
    if not last_payment:
        return 'OLAD00000001'
    reference_int = int(last_payment.reference_no.split('OLAD')[-1])
    return 'OLAD' + str(reference_int + 1).zfill(8)


def increment_refund_reference():
    last_refund = Refund.objects.all().order_by('id').last()
    if not last_refund:
        return 'RFND00000001'
    reference_int = int(last_refund.reference_no.split('RFND')[-1])
    return 'RFND' + str(reference_int + 1).zfill(8)


# Create your models here.
class PaymentLog(models.Model):
    enrolled = models.ForeignKey(Enrolled, on_delete=models.SET_NULL, blank=True, null=True, related_name='payments')
    amount_paid = models.DecimalField('amount paid', decimal_places=2, max_digits=10)
    payment_type = models.CharField('payment type', max_length=50, choices=PAYMENT_TYPE_CHOICES, default='stripe',
                                    null=False)
    reference_no = models.CharField('reference no', max_length=50, null=False, unique=True,
                                    default=increment_reference_number)
    payment_reference = models.CharField('cheque no', max_length=50, unique=True, blank=True, null=True)
    applied_discount = models.DecimalField('discount', blank=True, null=True, decimal_places=2, max_digits=10)
    discount = models.ForeignKey(Discount, verbose_name='discount code', on_delete=models.SET_NULL, blank=True,
                                 null=True)
    amount_owed = models.DecimalField('amount owed', null=True, blank=True, decimal_places=2, max_digits=10)
    has_applied_discount = models.BooleanField('has applied discount', default=False)
    note = models.TextField('note', null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField('created at', auto_now_add=True)

    def __str__(self):
        return self.reference_no

    def _apply_discount(self):
        if self.discount:
            # check if percentage
            if self.discount.percentage:
                discount = float(self.amount_paid) * float(self.discount.percentage/100)
                self.amount_paid -= discount
                self.applied_discount = discount
            else:
                self.amount_paid = float(self.amount_paid) - float(self.discount.amount)
                self.applied_discount = self.discount.amount

    def course_name(self):
        return self.enrolled.course

    def user_name(self):
        return self.enrolled.user

    def display_amount_paid(self):
        if self.amount_paid:
            return "${:0,.2f}".format(self.amount_paid)
        return self.amount_paid

    def display_discount(self):
        if self.applied_discount:
            return "${:0,.2f}".format(self.applied_discount)
        return self.applied_discount

    def display_amount_owed(self):
        if self.amount_owed:
            return "${:0,.2f}".format(self.amount_owed)
        return self.amount_owed

    def save(self, *args, **kwargs):
        if not self.has_applied_discount or kwargs.get('force_discount', None):
            self._apply_discount()
            self.has_applied_discount = True
        kwargs.pop('force_discount', None)
        super(PaymentLog, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'payment'
        verbose_name_plural = 'payments'

    reference_no.short_description = 'Payment Reference'
    display_amount_paid.short_description = 'Amount Paid'
    display_discount.short_description = 'Discount'
    display_amount_owed.short_description = 'Amount Owed'


class Refund(models.Model):
    enrolled = models.ForeignKey(Enrolled, on_delete=models.SET_NULL, blank=False, null=True)
    amount = models.DecimalField('refund amount', decimal_places=2, max_digits=10, null=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='refunded by', on_delete=models.SET_NULL,
                                   blank=True, null=True)
    created_at = models.DateTimeField('created at', auto_now_add=True)
    note = models.TextField('refund reason', null=True, blank=True)
    reference_no = models.CharField('reference no', max_length=50, null=False, unique=True,
                                    default=increment_refund_reference)

    def display_amount(self):
        if self.amount:
            return "${:0,.2f}".format(self.amount)
        return self.amount

    def course_name(self):
        if self.enrolled:
            return self.enrolled.course
        return self.enrolled

    def user_name(self):
        if self.enrolled:
            return self.enrolled.user
        return self.enrolled

payments/forms.py
from .models import PaymentLog, Refund, Enrolled
from django import forms


class PaymentForm(forms.ModelForm):
    class Meta:
        model = PaymentLog
        exclude = ('created_by', 'created_at', 'reference_no', 'applied_discount', 'amount_owed',
                   'has_applied_discount')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['amount_paid'].disabled = True
        self.fields['amount_paid'].label = 'Amount Owed'


class PaymentInlineForm(forms.ModelForm):
    class Meta:
        model = PaymentLog
        exclude = ('created_by', 'created_at', 'amount_paid', 'applied_discount', 'amount_owed', 'has_applied_discount')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['reference_no'].disabled = True

    def has_changed(self, *args, **kwargs):
        return True


class RefundForm(forms.ModelForm):
    amount_paid = forms.DecimalField(label='Amount Paid')

    class Meta:
        model = Refund
        exclude = ('created_at', 'created_by', 'enrolled', 'reference_no')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['amount_paid'].disabled = True

    def clean_amount(self):
        enrolled = Enrolled.objects.get(pk=self.initial.get('enrolled'))
        amount = self.cleaned_data.get('amount')
        if enrolled:
            if amount > enrolled.total_amount_paid:
                raise forms.ValidationError('Error. Refund amount cannot be greater than amount paid (${})'.format(
                    enrolled.total_amount_paid))
            return amount
        raise forms.ValidationError('Invalid enrolled record provided')

    field_order = ['amount_paid', 'amount', 'note']

payments/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from .models import PaymentLog


class PaymentHistoryView(ListView):
    template_name = 'payments/history.html'
    queryset = PaymentLog.objects.all()

    def get_queryset(self):
        return PaymentLog.objects.filter(enrolled__in=self.request.user.enrolled_courses.all())

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

templates/payments/history.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block title %} Olade - My Payment History {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'frontend/assets/css/datatables/datatables.min.css' %}">
{% endblock %}

{% block page-title %} My Payment History {% endblock %}
{% block breadcrumb %} Payment History {% endblock %}

{% block content %}
<!-- Begin Row -->
<div class="row flex-row">
    <div class="col-xl-12 col-12">
        <!-- Sorting -->
        <div class="widget has-shadow">
            <div class="widget-header bordered no-actions d-flex align-items-center">
                <h4>Payment History</h4>
            </div>
            <div class="widget-body">
                <div class="table-responsive">
                    <table id="sorting-table" class="table mb-0">
                        <thead>
                            <tr>
                                <th>Course</th>
                                <th>Payment Type</th>
                                <th>Amount Paid</th>
                                <th>Date Paid</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in object_list %}
                            <tr>
                                <td>{{ row.enrolled.course }}</td>
                                <td>{{ row.get_payment_type_display }}</td>
                                <td>{{ row.display_amount_paid }}</td>
                                <td>{{ row.created_at }}</td>
                                <td class="td-actions">
                                    <a href="#" title="Download receipt">
                                        <span class="badge-text badge-text-small info">
                                            Download
                                        </span>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End Sorting -->
    </div>
</div>
<!-- End Row -->
{% endblock %}

{% block custom_js %}
    <script src="{% static 'frontend/assets/vendors/js/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'frontend/assets/vendors/js/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'frontend/assets/js/components/tables/tables.js' %}"></script>
{% endblock %}