courses/urls.py
from django.urls import path
from .views import MyCoursesView, MyCertificatesView, CourseView

app_name = 'courses'

urlpatterns = [
    path('my-courses/', MyCoursesView.as_view(), name='my-courses'),
    path('my-certificates/', MyCertificatesView.as_view(), name='my-certificates'),
    path('<pk>/', CourseView.as_view(), name='detail'),
]

olade/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers


from users.views import UserLoginView
from courses.api_views import CourseApiViewSet, NewEnrolleeApiViewSet
from discounts.api_views import DiscountApiViewSet


# set up rest framework router
router = routers.DefaultRouter()
router.register(r'courses', CourseApiViewSet)
router.register(r'new-enrollee', base_name='new-enrollee', viewset=NewEnrolleeApiViewSet)
router.register(r'discount', DiscountApiViewSet)

# overwrite admin template variables
admin.site.site_header = 'Olade Administration'                    # default: "Django Administration"
admin.site.index_title = 'Administration'                 # default: "Site administration"
admin.site.site_title = 'Olade site admin'      # default: "Django site admin"

urlpatterns = [
    path('', UserLoginView.as_view()),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('courses/', include('courses.urls', namespace='courses')),
    path('payments/', include('payments.urls', namespace='payments')),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/models.py
from django.db import models
from django.conf import settings
from safedelete.models import SafeDeleteModel
from django.template.defaultfilters import slugify
from smart_selects.db_fields import ChainedForeignKey
from tinymce.models import HTMLField
from django.urls import reverse
from constance import config as custom_config
import datetime
from discounts.models import Discount


PAYMENT_STATUS_CHOICES = (
    ('partly', 'Part Payment'),
    ('paid', 'Fully Paid')
)

INITIAL_PAYMENT_TYPES = (
    ('partial', 'Part Payment'),
    ('full', 'Full Payment')
)

ENROLLED_STATUS_CHOICES = (
    ('pending', 'Pending'),
    ('ongoing', 'Ongoing'),
    ('completed', 'Completed')
)


def course_image_path(instance, filename):
    # for file uploads
    return 'images/events/events/{0}/{1}/{2}/{3}'.format(datetime.datetime.now().year, datetime.datetime.now().month,
                                                         datetime.datetime.now().day, filename)


class Courses(SafeDeleteModel):
    name = models.CharField('name', null=False, max_length=100)
    slug = models.CharField('slug', null=False, max_length=100)
    course_code = models.CharField('course code', null=True, blank=True, max_length=50)
    short_description = models.TextField('short description', max_length=300)
    learning_and_outcome = HTMLField('learning and outcome', blank=True, null=True)
    outline = HTMLField('outline', blank=True, null=True)
    overview = models.TextField('overview', blank=False, null=False)
    pre_requisites = models.TextField('pre-requisites', blank=False, null=False)
    strategy = models.TextField('course strategy', blank=True, null=True)
    tools_and_technology = models.TextField('tools and Technologies', blank=True, null=True)
    base_fee = models.DecimalField('base course fee', decimal_places=2, max_digits=10)
    image = models.ImageField('image', upload_to=course_image_path)
    is_active = models.BooleanField('is active', default=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='created_courses', on_delete=models.SET_NULL,
                                   null=True)
    created_at = models.DateTimeField('created at', auto_now_add=True)
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Enrolled', through_fields=('course', 'user'))

    def students_count(self):
        return self.students.count()

    def modules_count(self):
        return self.modules.count()

    @property
    def get_max_module_position(self):
        if self.modules_count() == 0:
            return 0
        return self.modules.aggregate(models.Max('order'))['order__max']

    @property
    def get_first_module(self):
        return self.modules.order_by('order').first()

    @property
    def course_fee(self):
        return round(float(self.base_fee) * (1 + float(custom_config.HST_GST/100)), 2)

    def __str__(self):
        return self.name

    def display_base_fee(self):
        return "${:0,.2f}".format(self.base_fee)

    def display_fee(self):
        return "${:0,.2f}".format(self.course_fee)

    def save(self, *args, **kwargs):
        # Overwrite save to allow for slug creation
        self.slug = slugify(self.name)
        super(Courses, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'course'
        verbose_name_plural = 'courses'

    # labels
    display_fee.short_description = 'Total Fee'
    display_base_fee.short_description = 'Course Fee'
    students_count.short_description = 'Students'
    modules_count.short_description = 'Modules'


class Modules(SafeDeleteModel):
    course = models.ForeignKey(Courses, related_name='modules', on_delete=models.CASCADE)
    name = models.CharField('name', blank=False, max_length=100)
    description = models.TextField('description')
    access_code = models.CharField('media code', max_length=100, null=True, blank=True)
    order = models.IntegerField('position')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='created_modules', on_delete=models.CASCADE)
    created_at = models.DateTimeField('created at', auto_now_add=True)
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='modules', through="EnrolledModules")

    def __str__(self):
        return "{}: {}".format(self.order, self.name)

    class Meta:
        unique_together = ('course', 'order')
        # order_by = 'order'
        verbose_name = 'module'
        verbose_name_plural = 'modules'


class Enrolled(SafeDeleteModel):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='enrolled_courses')
    status = models.CharField(max_length=50, choices=ENROLLED_STATUS_CHOICES, default='ongoing')
    payment_status = models.CharField(max_length=50, choices=PAYMENT_STATUS_CHOICES, default='paid', null=False)
    current_module = ChainedForeignKey(Modules, chained_field='course', chained_model_field='course', show_all=False,
                                       auto_choose=True, on_delete=models.SET_NULL, null=True)
    date_enrolled = models.DateTimeField('date enrolled', auto_now_add=True)

    class Meta:
        unique_together = ('course', 'user')
        verbose_name_plural = 'Enrollments'
        verbose_name = 'Enrollment'

    def __str__(self):
        return "{}: {}".format(self.course, self.user)

    @property
    def last_payment(self):
        if self.payments:
            return self.payments.order_by('-created_at').first()
        return None

    @property
    def total_amount_paid(self):
        total = 0
        if self.payments:
            for payment in self.payments.all():
                total += payment.amount_paid
        return total


class EnrolledModules(SafeDeleteModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    module = models.ForeignKey(Modules, on_delete=models.CASCADE)
    enrolled = models.ForeignKey(Enrolled, related_name='modules', on_delete=models.CASCADE)
    date_activated = models.DateTimeField('date activated', auto_now_add=True)
    days = models.IntegerField('open for', default=7)
    expires = models.DateTimeField('date expires')

    class Meta:
        unique_together = ('user', 'module')

    def set_expires(self):
        if getattr(self, 'days'):
            self.expires = datetime.datetime.now() + datetime.timedelta(days=self.days)


class PendingEnrollments(SafeDeleteModel):
    first_name = models.CharField('first name', max_length=100, null=False, blank=False)
    last_name = models.CharField('last name', max_length=100, null=False, blank=False)
    email = models.EmailField('email', max_length=100, null=False, blank=False)
    phone_number = models.CharField('phone number', max_length=100, null=True, blank=True)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    payment_type = models.CharField(max_length=10, null=True, choices=INITIAL_PAYMENT_TYPES)
    payment_status = models.CharField(max_length=50, default='unpaid', null=True)
    discount = models.ForeignKey(Discount, on_delete=models.SET_NULL, blank=True, null=True)
    date_created = models.DateTimeField('date created', auto_now_add=True)

courses/forms.py
from .models import Modules, EnrolledModules, Enrolled
from django import forms


class EnrolledForm(forms.ModelForm):
    course_fee = forms.FloatField(label='Course Fee', disabled=True, required=False)

    class Meta:
        model = Enrolled
        exclude = ('date_enrolled', 'initial_payment_type')


class ModuleForm(forms.ModelForm):
    class Meta:
        model = Modules
        exclude = ('created_at', 'students')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['created_by'].disabled = True
        self.fields['course'].disabled = True


class OpenEnrolledModuleForm(forms.ModelForm):
    class Meta:
        model = EnrolledModules
        exclude = ('date_activated', 'expires')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['enrolled'].disabled = True
        self.fields['user'].disabled = True

courses/views.py
from django.views.generic import FormView, CreateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from .models import Courses, Enrolled


class CourseView(DetailView):
    template_name = "courses/course_detail.html"

    def get_queryset(self):
        return Enrolled.objects.filter(user=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class MyCoursesView(ListView):
    template_name = "courses/my_courses_list.html"

    def get_queryset(self):
        return Enrolled.objects.filter(user=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class MyCertificatesView(ListView):
    template_name = 'courses/my_certificates_list.html'
    queryset = Enrolled.objects.all()

    def get_queryset(self):
        return Enrolled.objects.filter(user=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

templates/courses/course_detail.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block title %} Olade - My Courses {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'frontend/assets/css/datatables/datatables.min.css' %}">
{% endblock %}

{% block page-title %} {{ object.course.course_code }}: {{ object.course }} {% endblock %}
{% block breadcrumb %} {{ object.course.course_code }}: {{ object.course }} {% endblock %}


{% block content %}
    <div class="row flex-row">
        <div class="col-xl-9 col-9">
            <div class="widget has-shadow">
                <div class="widget-header bordered no-actions d-flex align-items-center">
                    <h3>Course Content</h3>
                </div>
                <div class="widget-body">
                    <div>
                        {{ object.course.description | safe }}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-3">
            <div class="widget has-shadow">
                <div class="widget-header bordered no-actions d-flex align-items-center">
                    <h3>Course Outline</h3>
                </div>
                <div class="widget-body">
                    <div>
                        {{ object.course.outline | safe }}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-12 col-12">
            <div class="widget has-shadow">
                <div class="widget-header bordered no-actions d-flex align-items-center">
                    <h3>Course Modules</h3>
                </div>
                <div class="widget-body">
                    <div class="table-responsive">
                    <table id="sorting-table" class="table mb-0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Module</th>
                                <th>Date Access Granted</th>
                                <th>Date Expired</th>
                                <th><span style="width:100px;">Status</span></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in object.course.modules.all %}
                            <tr>
                                <td>{{ row.order }}</td>
                                <td>{{ row.name }}</td>
                                <td>

                                </td>
                                <td></td>
                                <td></td>
                                <td>
                                    <span style="width:100px;">
                                        {% if row.payment_status == 'paid' %}
                                            <span class="badge-text badge-text-small success">
                                        {% elif row.payment_status == 'partly' %}
                                            <span class="badge-text badge-text-small info">
                                        {% else %}
                                            <span class="badge-text badge-text-small danger">
                                        {% endif %}
                                                {{ row.get_payment_status_display }}
                                            </span>
                                    </span>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'frontend/assets/vendors/js/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'frontend/assets/vendors/js/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'frontend/assets/js/components/tables/tables.js' %}"></script>
{% endblock %}

templates/courses/my_certificates_list.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block title %} Olade - My Certificates {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'frontend/assets/css/datatables/datatables.min.css' %}">
{% endblock %}

{% block page-title %} My Certificates {% endblock %}
{% block breadcrumb %} My Certificates {% endblock %}

{% block content %}
<!-- Begin Row -->
<div class="row flex-row">
    <div class="col-xl-12 col-12">
        <!-- Sorting -->
        <div class="widget has-shadow">
            <div class="widget-header bordered no-actions d-flex align-items-center">
                <h4>My Certificates</h4>
            </div>
            <div class="widget-body">
                <div class="table-responsive">
                    <table id="sorting-table" class="table mb-0">
                        <thead>
                            <tr>
                                <th>Course</th>
                                <th>Date Completed</th>
                                <th><span style="width:100px;">Payment Status</span></th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in objects %}
                            <tr>
                                <td>{{ row.course }}</td>
                                <td>{{ row.date_enrolled }}</td>
                                <td>
                                    <span style="width:100px;">
                                        {% if row.payment_status == 'paid' %}
                                            <span class="badge-text badge-text-small success">Paid</span>
                                        {% elif row.payment_status == 'partly' %}
                                            <span class="badge-text badge-text-small info">Part Payment</span>
                                        {% else %}
                                            <span class="badge-text badge-text-small danger">Unpaid</span>
                                        {% endif %}
                                    </span>
                                </td>
                                <td class="td-actions">
                                    <a href="#"><i class="la la-download download"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End Sorting -->
    </div>
</div>
<!-- End Row -->
{% endblock %}

{% block custom_js %}
    <script src="{% static 'frontend/assets/vendors/js/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'frontend/assets/vendors/js/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'frontend/assets/js/components/tables/tables.js' %}"></script>
{% endblock %}

templates/courses/my_courses_list.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block title %} Olade - My Courses {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'frontend/assets/css/datatables/datatables.min.css' %}">
{% endblock %}

{% block page-title %} My Courses {% endblock %}
{% block breadcrumb %} My Courses {% endblock %}

{% block content %}
<!-- Begin Row -->
<div class="row flex-row">
    <div class="col-xl-12 col-12">
        <!-- Sorting -->
        <div class="widget has-shadow">
            <div class="widget-header bordered no-actions d-flex align-items-center">
                <h4>Enrolled Courses</h4>
            </div>
            <div class="widget-body">
                <div class="table-responsive">
                    <table id="sorting-table" class="table mb-0">
                        <thead>
                            <tr>
                                <th>Course</th>
                                <th>Current Module</th>
                                <th>Date Registered</th>
                                <th><span style="width:100px;">Status</span></th>
                                <th>Fee</th>
                                <th><span style="width:100px;">Payment Status</span></th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in object_list %}
                            <tr>
                                <td>{{ row.course }}</td>
                                <td>{{ row.current_module }}</td>
                                <td>{{ row.date_enrolled }}</td>
                                <td>{{ row.get_status_display }}</td>
                                <td>
                                    {{ row.course.display_fee }}
                                </td>
                                <td>
                                    <span style="width:100px;">
                                        {% if row.payment_status == 'paid' %}
                                            <span class="badge-text badge-text-small success">
                                        {% elif row.payment_status == 'partly' %}
                                            <span class="badge-text badge-text-small info">
                                        {% else %}
                                            <span class="badge-text badge-text-small danger">
                                        {% endif %}
                                                {{ row.get_payment_status_display }}
                                            </span>
                                    </span>
                                </td>
                                <td class="td-actions">
                                    <!--
                                    <a href="#"><i class="la la-edit edit"></i></a>
                                    <a href="#"><i class="la la-close delete"></i></a>
                                    -->
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End Sorting -->
    </div>
</div>
<!-- End Row -->
{% endblock %}

{% block custom_js %}
    <script src="{% static 'frontend/assets/vendors/js/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'frontend/assets/vendors/js/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'frontend/assets/js/components/tables/tables.js' %}"></script>
{% endblock %}